// Code generated by protoc-gen-go.
// source: chord.proto
// DO NOT EDIT!

/*
Package chordMsgs is a generated protocol buffer package.

It is generated from these files:
	chord.proto

It has these top-level messages:
	SendIdMessage
	FingerMessage
	PredMessage
	SendFingersMessage
	ChordMessage
	NetworkMessage
*/
package chordMsgs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChordMessage_Command int32

const (
	ChordMessage_Ping       ChordMessage_Command = 1
	ChordMessage_Pong       ChordMessage_Command = 2
	ChordMessage_GetPred    ChordMessage_Command = 3
	ChordMessage_GetId      ChordMessage_Command = 4
	ChordMessage_GetFingers ChordMessage_Command = 5
	ChordMessage_ClaimPred  ChordMessage_Command = 6
	ChordMessage_GetSucc    ChordMessage_Command = 7
)

var ChordMessage_Command_name = map[int32]string{
	1: "Ping",
	2: "Pong",
	3: "GetPred",
	4: "GetId",
	5: "GetFingers",
	6: "ClaimPred",
	7: "GetSucc",
}
var ChordMessage_Command_value = map[string]int32{
	"Ping":       1,
	"Pong":       2,
	"GetPred":    3,
	"GetId":      4,
	"GetFingers": 5,
	"ClaimPred":  6,
	"GetSucc":    7,
}

func (x ChordMessage_Command) Enum() *ChordMessage_Command {
	p := new(ChordMessage_Command)
	*p = x
	return p
}
func (x ChordMessage_Command) String() string {
	return proto.EnumName(ChordMessage_Command_name, int32(x))
}
func (x *ChordMessage_Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChordMessage_Command_value, data, "ChordMessage_Command")
	if err != nil {
		return err
	}
	*x = ChordMessage_Command(value)
	return nil
}
func (ChordMessage_Command) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type SendIdMessage struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SendIdMessage) Reset()                    { *m = SendIdMessage{} }
func (m *SendIdMessage) String() string            { return proto.CompactTextString(m) }
func (*SendIdMessage) ProtoMessage()               {}
func (*SendIdMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendIdMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type FingerMessage struct {
	Address          *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FingerMessage) Reset()                    { *m = FingerMessage{} }
func (m *FingerMessage) String() string            { return proto.CompactTextString(m) }
func (*FingerMessage) ProtoMessage()               {}
func (*FingerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FingerMessage) GetAddress() string {
	if m != nil && m.Address != nil {
		return *m.Address
	}
	return ""
}

func (m *FingerMessage) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

type PredMessage struct {
	Pred             *FingerMessage `protobuf:"bytes,1,req,name=pred" json:"pred,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PredMessage) Reset()                    { *m = PredMessage{} }
func (m *PredMessage) String() string            { return proto.CompactTextString(m) }
func (*PredMessage) ProtoMessage()               {}
func (*PredMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PredMessage) GetPred() *FingerMessage {
	if m != nil {
		return m.Pred
	}
	return nil
}

type SendFingersMessage struct {
	Fingers          []*FingerMessage `protobuf:"bytes,1,rep,name=fingers" json:"fingers,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SendFingersMessage) Reset()                    { *m = SendFingersMessage{} }
func (m *SendFingersMessage) String() string            { return proto.CompactTextString(m) }
func (*SendFingersMessage) ProtoMessage()               {}
func (*SendFingersMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SendFingersMessage) GetFingers() []*FingerMessage {
	if m != nil {
		return m.Fingers
	}
	return nil
}

type ChordMessage struct {
	Cmd              *ChordMessage_Command `protobuf:"varint,1,req,name=cmd,enum=chordMsgs.ChordMessage_Command" json:"cmd,omitempty"`
	Cpmsg            *PredMessage          `protobuf:"bytes,2,opt,name=cpmsg" json:"cpmsg,omitempty"`
	Sidmsg           *SendIdMessage        `protobuf:"bytes,4,opt,name=sidmsg" json:"sidmsg,omitempty"`
	Sfmsg            *SendFingersMessage   `protobuf:"bytes,5,opt,name=sfmsg" json:"sfmsg,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *ChordMessage) Reset()                    { *m = ChordMessage{} }
func (m *ChordMessage) String() string            { return proto.CompactTextString(m) }
func (*ChordMessage) ProtoMessage()               {}
func (*ChordMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ChordMessage) GetCmd() ChordMessage_Command {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return ChordMessage_Ping
}

func (m *ChordMessage) GetCpmsg() *PredMessage {
	if m != nil {
		return m.Cpmsg
	}
	return nil
}

func (m *ChordMessage) GetSidmsg() *SendIdMessage {
	if m != nil {
		return m.Sidmsg
	}
	return nil
}

func (m *ChordMessage) GetSfmsg() *SendFingersMessage {
	if m != nil {
		return m.Sfmsg
	}
	return nil
}

type NetworkMessage struct {
	Proto            *uint32 `protobuf:"varint,1,req,name=proto" json:"proto,omitempty"`
	Msg              *string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NetworkMessage) Reset()                    { *m = NetworkMessage{} }
func (m *NetworkMessage) String() string            { return proto.CompactTextString(m) }
func (*NetworkMessage) ProtoMessage()               {}
func (*NetworkMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NetworkMessage) GetProto() uint32 {
	if m != nil && m.Proto != nil {
		return *m.Proto
	}
	return 0
}

func (m *NetworkMessage) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*SendIdMessage)(nil), "chordMsgs.SendIdMessage")
	proto.RegisterType((*FingerMessage)(nil), "chordMsgs.FingerMessage")
	proto.RegisterType((*PredMessage)(nil), "chordMsgs.PredMessage")
	proto.RegisterType((*SendFingersMessage)(nil), "chordMsgs.SendFingersMessage")
	proto.RegisterType((*ChordMessage)(nil), "chordMsgs.ChordMessage")
	proto.RegisterType((*NetworkMessage)(nil), "chordMsgs.NetworkMessage")
	proto.RegisterEnum("chordMsgs.ChordMessage_Command", ChordMessage_Command_name, ChordMessage_Command_value)
}

func init() { proto.RegisterFile("chord.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6a, 0xb3, 0x40,
	0x14, 0xc5, 0x71, 0xd4, 0xf8, 0x79, 0xfd, 0x94, 0x61, 0x28, 0xc5, 0x4d, 0x49, 0x70, 0x95, 0x45,
	0x90, 0xd6, 0x6e, 0x5a, 0xba, 0x0c, 0x34, 0xcd, 0x22, 0x25, 0x4c, 0x9e, 0x40, 0x9c, 0x89, 0x95,
	0x56, 0x0d, 0x33, 0x96, 0x3e, 0x5b, 0xdf, 0xae, 0x38, 0x7f, 0x82, 0xe9, 0xa2, 0xbb, 0x7b, 0xf5,
	0x77, 0xce, 0x9c, 0x39, 0x0c, 0x44, 0xd5, 0x5b, 0x2f, 0x58, 0x7e, 0x12, 0xfd, 0xd0, 0x93, 0x50,
	0x2d, 0x3b, 0x59, 0xcb, 0x6c, 0x0e, 0xf1, 0x81, 0x77, 0x6c, 0xcb, 0x76, 0x5c, 0xca, 0xb2, 0xe6,
	0x24, 0x01, 0xd4, 0xb0, 0xd4, 0x59, 0xa0, 0x65, 0x48, 0x51, 0xc3, 0xb2, 0x47, 0x88, 0x9f, 0x9b,
	0xae, 0xe6, 0xc2, 0x02, 0x29, 0x04, 0x25, 0x63, 0x82, 0x4b, 0x69, 0x28, 0xbb, 0x1a, 0x29, 0x3a,
	0x4b, 0x9f, 0x20, 0xda, 0x0b, 0x7e, 0x76, 0x5e, 0x81, 0x77, 0x12, 0x5c, 0x7b, 0x47, 0x45, 0x9a,
	0x9f, 0x43, 0xe4, 0x17, 0x07, 0x50, 0x45, 0x65, 0x2f, 0x40, 0xc6, 0x60, 0xfa, 0x97, 0xb4, 0x1e,
	0x05, 0x04, 0x47, 0xfd, 0x25, 0x75, 0x16, 0xee, 0x9f, 0x36, 0x16, 0xcc, 0xbe, 0x11, 0xfc, 0x5f,
	0x2b, 0xc8, 0x98, 0xdc, 0x81, 0x5b, 0xb5, 0x3a, 0x47, 0x52, 0xcc, 0x27, 0x06, 0x53, 0x2a, 0x5f,
	0xf7, 0x6d, 0x5b, 0x76, 0x8c, 0x8e, 0x2c, 0x59, 0x81, 0x5f, 0x9d, 0x5a, 0x59, 0xa7, 0x68, 0xe1,
	0x2c, 0xa3, 0xe2, 0x7a, 0x22, 0x9a, 0x5c, 0x91, 0x6a, 0x88, 0xdc, 0xc2, 0x4c, 0x36, 0x6c, 0xc4,
	0x3d, 0x85, 0x4f, 0x43, 0x5e, 0xb4, 0x4d, 0x0d, 0x47, 0xee, 0xc1, 0x97, 0xc7, 0x51, 0xe0, 0x2b,
	0xc1, 0xcd, 0x2f, 0xc1, 0x65, 0x0b, 0x54, 0xb3, 0x59, 0x09, 0x81, 0x09, 0x49, 0xfe, 0x81, 0xb7,
	0x6f, 0xba, 0x1a, 0x3b, 0x6a, 0xea, 0xbb, 0x1a, 0x23, 0x12, 0x41, 0xb0, 0xe1, 0xc3, 0x18, 0x0f,
	0xbb, 0x24, 0x04, 0x7f, 0xc3, 0x87, 0x2d, 0xc3, 0x1e, 0x49, 0x00, 0x36, 0x7c, 0x30, 0x96, 0xd8,
	0x27, 0x31, 0x84, 0xeb, 0x8f, 0xb2, 0x69, 0x15, 0x39, 0x33, 0xb2, 0xc3, 0x67, 0x55, 0xe1, 0x20,
	0x7b, 0x80, 0xe4, 0x95, 0x0f, 0x5f, 0xbd, 0x78, 0xb7, 0xe5, 0x5d, 0x81, 0xaf, 0x1e, 0x91, 0xaa,
	0x2f, 0xa6, 0x7a, 0x21, 0x18, 0x5c, 0xdb, 0x4e, 0x48, 0xc7, 0xf1, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x47, 0x9d, 0x78, 0x5f, 0x71, 0x02, 0x00, 0x00,
}
